language: julia
os:
  - linux
  - osx
julia:
  - 1.1
notifications:
  email: false
branches:
  only:
  - master
  - /release-.*/
  - /v(\d+)\.(\d+)\.(\d+)/
after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("MimiFUND")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
